PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS admins (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, password_salt TEXT NOT NULL, iterations INTEGER NOT NULL DEFAULT 100000, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_sessions (id TEXT PRIMARY KEY, admin_id TEXT NOT NULL REFERENCES admins(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_token ON admin_sessions(token_hash);
CREATE TABLE IF NOT EXISTS login_attempts (id INTEGER PRIMARY KEY AUTOINCREMENT, ip_hash TEXT NOT NULL, attempted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, success INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_login_attempts_ip_time ON login_attempts(ip_hash, attempted_at);

CREATE TABLE IF NOT EXISTS categories (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, image_url TEXT, active INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, sku TEXT NOT NULL UNIQUE, price_cents INTEGER NOT NULL, sale_price_cents INTEGER, description TEXT NOT NULL DEFAULT '', short_description TEXT NOT NULL DEFAULT '', image_url TEXT, stock INTEGER NOT NULL DEFAULT 0, low_stock_threshold INTEGER NOT NULL DEFAULT 5, ingredients TEXT NOT NULL DEFAULT '', allergens TEXT NOT NULL DEFAULT '', dietary_labels TEXT NOT NULL DEFAULT '', featured INTEGER NOT NULL DEFAULT 0, best_seller INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_products_active_order ON products(active, display_order);
CREATE TABLE IF NOT EXISTS product_variants (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, name TEXT NOT NULL, sku TEXT NOT NULL UNIQUE, price_cents INTEGER NOT NULL, sale_price_cents INTEGER, stock INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS product_categories (product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE, PRIMARY KEY(product_id, category_id));
CREATE TABLE IF NOT EXISTS lollies (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT NOT NULL DEFAULT '', category TEXT NOT NULL DEFAULT '', dietary_info TEXT NOT NULL DEFAULT '', allergen_info TEXT NOT NULL DEFAULT '', image_url TEXT, stock INTEGER NOT NULL DEFAULT 0, available INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS jar_sizes (id TEXT PRIMARY KEY, name TEXT NOT NULL, volume TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', price_cents INTEGER NOT NULL, image_url TEXT, max_selections INTEGER NOT NULL, available INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, order_number TEXT NOT NULL UNIQUE, stripe_session_id TEXT UNIQUE, stripe_payment_intent_id TEXT, customer_name TEXT, email TEXT, phone TEXT, shipping_address_json TEXT, subtotal_cents INTEGER NOT NULL, shipping_cents INTEGER NOT NULL DEFAULT 0, total_cents INTEGER NOT NULL, payment_status TEXT NOT NULL DEFAULT 'pending', fulfilment_status TEXT NOT NULL DEFAULT 'new', tracking_number TEXT, admin_notes TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(payment_status, fulfilment_status);
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id TEXT REFERENCES products(id), jar_size_id TEXT REFERENCES jar_sizes(id), name TEXT NOT NULL, sku TEXT, variant_name TEXT, unit_price_cents INTEGER NOT NULL, quantity INTEGER NOT NULL, custom_mix_json TEXT);
CREATE TABLE IF NOT EXISTS custom_mix_selections (id TEXT PRIMARY KEY, order_item_id TEXT NOT NULL REFERENCES order_items(id) ON DELETE CASCADE, lolly_id TEXT NOT NULL REFERENCES lollies(id), lolly_name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS stripe_events (event_id TEXT PRIMARY KEY, event_type TEXT NOT NULL, processed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS shipping_settings (id TEXT PRIMARY KEY, method TEXT NOT NULL UNIQUE, label TEXT NOT NULL, rate_cents INTEGER NOT NULL DEFAULT 0, free_threshold_cents INTEGER, enabled INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS testimonials (id TEXT PRIMARY KEY, name TEXT NOT NULL, review TEXT NOT NULL, rating INTEGER NOT NULL DEFAULT 5, image_url TEXT, active INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS faqs (id TEXT PRIMARY KEY, question TEXT NOT NULL, answer TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, display_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS contact_enquiries (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, subject TEXT, order_number TEXT, message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO categories VALUES ('cat-pickmix','Pick n Mix','pick-n-mix',NULL,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('cat-jars','Lolly Jars','lolly-jars',NULL,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('cat-sour','Sour Lollies','sour-lollies',NULL,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('cat-gummies','Gummies','gummies',NULL,1,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('cat-party','Party Packs','party-packs',NULL,1,5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('cat-vegan','Vegan Options','vegan-options',NULL,1,6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO products VALUES ('prod-550','550ml Pick n Mix Jar','550ml-pick-n-mix','VK-550',1495,NULL,'Build a custom jar from your favourite lollies.','Choose up to six flavours.',NULL,100,10,'Owner to confirm','Owner to confirm','',1,1,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('prod-1l','1L Pick n Mix Jar','1l-pick-n-mix','VK-1L',2495,NULL,'Build a generous custom jar from your favourite lollies.','Choose up to eight flavours.',NULL,100,10,'Owner to confirm','Owner to confirm','',1,1,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('prod-sour','Sour Mix','sour-mix','VK-SOUR',1695,NULL,'A tangy ready-made mix.','A colourful sour selection.',NULL,50,5,'Owner to confirm','Owner to confirm','',1,0,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('prod-gummy','Gummy Mix','gummy-mix','VK-GUMMY',1695,NULL,'A chewy ready-made mix.','A fun gummy selection.',NULL,50,5,'Owner to confirm','Owner to confirm','',1,0,1,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('prod-sweet','Sweet Mix','sweet-mix','VK-SWEET',1595,NULL,'A classic ready-made sweet mix.','Something sweet for everyone.',NULL,50,5,'Owner to confirm','Owner to confirm','',0,0,1,5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('prod-party','Party Mix','party-mix','VK-PARTY',3995,NULL,'A larger mix for celebrations.','Party-ready sweet selection.',NULL,30,5,'Owner to confirm','Owner to confirm','',0,0,1,6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO product_categories VALUES ('prod-550','cat-pickmix'),('prod-1l','cat-jars'),('prod-sour','cat-sour'),('prod-gummy','cat-gummies'),('prod-party','cat-party');
INSERT OR IGNORE INTO jar_sizes VALUES ('jar-550','550ml Jar','550ml','Choose up to six flavours.',1495,NULL,6,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('jar-1l','1 Litre Jar','1 Litre','Choose up to eight flavours.',2495,NULL,8,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO lollies VALUES ('lol-gummy','Gummy Bears','gummy-bears','Colourful gummy bears.','Gummies','Owner to confirm','Owner to confirm',NULL,100,1,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('lol-cola','Cola Bottles','cola-bottles','Classic cola bottles.','Gummies','Owner to confirm','Owner to confirm',NULL,100,1,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('lol-worms','Sour Worms','sour-worms','Tangy sour worms.','Sour','Owner to confirm','Owner to confirm',NULL,100,1,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('lol-peach','Peach Rings','peach-rings','Sweet peach rings.','Gummies','Owner to confirm','Owner to confirm',NULL,100,1,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('lol-snakes','Snakes','snakes','Colourful lolly snakes.','Gummies','Owner to confirm','Owner to confirm',NULL,100,1,5,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('lol-milk','Milk Bottles','milk-bottles','Creamy milk bottles.','Classic','Owner to confirm','Owner to confirm',NULL,100,1,6,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('lol-beans','Jelly Beans','jelly-beans','A rainbow of jelly beans.','Classic','Owner to confirm','Owner to confirm',NULL,100,1,7,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('lol-strawberry','Strawberries and Cream','strawberries-cream','A creamy strawberry favourite.','Classic','Owner to confirm','Owner to confirm',NULL,100,1,8,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO shipping_settings VALUES ('ship-standard','standard','Standard shipping',995,7500,1,1),('ship-express','express','Express shipping',1495,NULL,1,2),('ship-pickup','pickup','Local pickup',0,NULL,0,3);
INSERT OR IGNORE INTO site_settings VALUES ('announcement','Fresh Pick n Mix Lollies Delivered Australia Wide',CURRENT_TIMESTAMP),('hero_title','PICK. MIX. ENJOY.',CURRENT_TIMESTAMP),('hero_subtitle','Build your perfect lolly mix and get it delivered straight to your door.',CURRENT_TIMESTAMP),('facebook_url','https://www.facebook.com/vikingkinglolliepicknmix',CURRENT_TIMESTAMP),('contact_email','',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO faqs VALUES ('faq-1','How does Pick n Mix work?','Choose your jar, select your favourite flavours and add the finished mix to your bag.',1,1),('faq-2','How many lollies can I choose?','The number of flavour choices depends on the selected jar size.',1,2),('faq-3','Do you deliver Australia wide?','Final shipping availability and rates will be confirmed by the store owner.',1,3),('faq-4','What allergens are present?','Ingredients and allergens vary. Please review the confirmed product information before ordering.',1,4);
