import type { Env } from "./types";
import { b64, cleanText, constantTimeEqual, fromB64, id, json, pbkdf2, requireAdmin, sha256, verifyTurnstile } from "./utils";

const corsHeaders = { "X-Content-Type-Options":"nosniff", "Referrer-Policy":"strict-origin-when-cross-origin", "Permissions-Policy":"camera=(), microphone=(), geolocation=()" };

async function catalogue(env: Env) {
  const [products,jars,lollies,categories,settings] = await Promise.all([
    env.DB.prepare("SELECT p.id,p.name,p.slug,p.sku,p.price_cents,p.sale_price_cents,p.short_description,p.image_url,p.stock,p.featured,p.best_seller,COALESCE(c.name,'Uncategorised') category_name FROM products p LEFT JOIN product_categories pc ON pc.product_id=p.id LEFT JOIN categories c ON c.id=pc.category_id WHERE p.active=1 ORDER BY p.display_order,p.name").all(),
    env.DB.prepare("SELECT id,name,volume,description,price_cents,max_selections,image_url,available FROM jar_sizes WHERE available=1 ORDER BY display_order").all(),
    env.DB.prepare("SELECT id,name,description,category,dietary_info,allergen_info,image_url,available FROM lollies WHERE available=1 AND stock>0 ORDER BY display_order").all(),
    env.DB.prepare("SELECT id,name,slug,image_url FROM categories WHERE active=1 ORDER BY display_order").all(),
    env.DB.prepare("SELECT key,value FROM site_settings").all<{key:string,value:string}>()
  ]);
  return json({ products:products.results, jars:jars.results, lollies:lollies.results, categories:categories.results, settings:Object.fromEntries(settings.results.map(x=>[x.key,x.value])) },200,{"Cache-Control":"public, max-age=60, s-maxage=300"});
}

type IncomingItem={product_id?:string;jar_size_id?:string;quantity?:number;lolly_ids?:string[]};
function shippingForSku(sku:string){
  if(sku==='VK-BUNDLE-10')return {standard:1500,express:1800};
  if(sku.startsWith('VK-700'))return {standard:950,express:950};
  if(sku.startsWith('VK-1L')||sku.startsWith('VK-3L'))return {standard:800,express:950};
  return {standard:850,express:950};
}
async function checkout(req:Request,env:Env){
  if(!env.STRIPE_SECRET_KEY) return json({error:"Stripe is not configured"},503);
  const body=await req.json().catch(()=>({})) as {items?:IncomingItem[]}; if(!Array.isArray(body.items)||!body.items.length||body.items.length>30) return json({error:"Invalid cart"},400);
  const verified:{name:string;sku:string;unit:number;qty:number;productId?:string;jarId?:string;lollyIds?:string[];lollyNames?:string[]}[]=[];
  for(const raw of body.items){
    const qty=Math.max(1,Math.min(20,Math.floor(Number(raw.quantity)||1)));
    if(raw.jar_size_id){
      const jar=await env.DB.prepare("SELECT id,name,volume,price_cents,max_selections FROM jar_sizes WHERE id=? AND available=1").bind(raw.jar_size_id).first<{id:string;name:string;volume:string;price_cents:number;max_selections:number}>();
      if(!jar) return json({error:"A selected jar is unavailable"},409);
      const unique=[...new Set(raw.lolly_ids||[])]; if(!unique.length||unique.length>jar.max_selections) return json({error:`Choose between 1 and ${jar.max_selections} flavours`},400);
      const marks=unique.map(()=>'?').join(','); const lollyRows=await env.DB.prepare(`SELECT id,name FROM lollies WHERE id IN (${marks}) AND available=1 AND stock>0`).bind(...unique).all<{id:string;name:string}>();
      if(lollyRows.results.length!==unique.length) return json({error:"A selected lolly is unavailable"},409);
      verified.push({name:`Custom ${jar.volume} Pick n Mix`,sku:`CUSTOM-${jar.volume}`,unit:jar.price_cents,qty,jarId:jar.id,lollyIds:unique,lollyNames:lollyRows.results.map(x=>x.name)});
    } else if(raw.product_id){
      const product=await env.DB.prepare("SELECT id,name,sku,price_cents,sale_price_cents,stock FROM products WHERE id=? AND active=1").bind(raw.product_id).first<{id:string;name:string;sku:string;price_cents:number;sale_price_cents:number|null;stock:number}>();
      if(!product||product.stock<qty) return json({error:"A selected product is unavailable or out of stock"},409);
      verified.push({name:product.name,sku:product.sku,unit:product.sale_price_cents??product.price_cents,qty,productId:product.id});
    } else return json({error:"Invalid cart item"},400);
  }
  const subtotal=verified.reduce((sum,x)=>sum+x.unit*x.qty,0); const orderId=id(); const orderNumber=`VK-${Date.now().toString().slice(-8)}`;
  const statements=[env.DB.prepare("INSERT INTO orders(id,order_number,subtotal_cents,total_cents) VALUES(?,?,?,?)").bind(orderId,orderNumber,subtotal,subtotal),...verified.map(item=>env.DB.prepare("INSERT INTO order_items(id,order_id,product_id,jar_size_id,name,sku,unit_price_cents,quantity,custom_mix_json) VALUES(?,?,?,?,?,?,?,?,?)").bind(id(),orderId,item.productId||null,item.jarId||null,item.name,item.sku,item.unit,item.qty,item.lollyIds?JSON.stringify({lolly_ids:item.lollyIds,lolly_names:item.lollyNames}):null))];
  await env.DB.batch(statements);
  const form=new URLSearchParams(); form.set("mode","payment"); form.set("success_url",`${env.APP_URL}/?checkout=success&session_id={CHECKOUT_SESSION_ID}`); form.set("cancel_url",`${env.APP_URL}/?checkout=cancelled`); form.set("customer_creation","always"); form.set("billing_address_collection","required"); form.set("shipping_address_collection[allowed_countries][0]","AU"); form.set("metadata[order_id]",orderId); form.set("metadata[order_number]",orderNumber);
  verified.forEach((item,i)=>{form.set(`line_items[${i}][price_data][currency]`,`aud`);form.set(`line_items[${i}][price_data][unit_amount]`,String(item.unit));form.set(`line_items[${i}][price_data][product_data][name]`,item.name);if(item.lollyNames?.length)form.set(`line_items[${i}][price_data][product_data][description]`,item.lollyNames.join(', '));form.set(`line_items[${i}][quantity]`,String(item.qty));});
  const shipping=verified.reduce((rates,item)=>{const itemRates=shippingForSku(item.sku);return {standard:Math.max(rates.standard,itemRates.standard),express:Math.max(rates.express,itemRates.express)}},{standard:0,express:0});
  form.set("shipping_options[0][shipping_rate_data][type]","fixed_amount");form.set("shipping_options[0][shipping_rate_data][fixed_amount][amount]",String(shipping.standard));form.set("shipping_options[0][shipping_rate_data][fixed_amount][currency]","aud");form.set("shipping_options[0][shipping_rate_data][display_name]","Standard postage");
  form.set("shipping_options[1][shipping_rate_data][type]","fixed_amount");form.set("shipping_options[1][shipping_rate_data][fixed_amount][amount]",String(shipping.express));form.set("shipping_options[1][shipping_rate_data][fixed_amount][currency]","aud");form.set("shipping_options[1][shipping_rate_data][display_name]","Express postage");
  const stripe=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,"Content-Type":"application/x-www-form-urlencoded"},body:form}); const result=await stripe.json() as {id?:string;url?:string;error?:{message:string}};
  if(!stripe.ok||!result.id||!result.url){await env.DB.prepare("UPDATE orders SET payment_status='checkout_failed',admin_notes=? WHERE id=?").bind(result.error?.message||"Stripe error",orderId).run();return json({error:"Unable to start checkout"},502);}
  await env.DB.prepare("UPDATE orders SET stripe_session_id=? WHERE id=?").bind(result.id,orderId).run(); return json({url:result.url});
}

async function hmacHex(secret:string,payload:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(payload));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function webhook(req:Request,env:Env){
  const raw=await req.text();const header=req.headers.get("Stripe-Signature")||"";const parts=Object.fromEntries(header.split(',').map(x=>x.split('=',2))) as Record<string,string>;if(!parts.t||!parts.v1)return json({error:"Missing signature"},400);
  if(Math.abs(Date.now()/1000-Number(parts.t))>300)return json({error:"Expired signature"},400);const expected=await hmacHex(env.STRIPE_WEBHOOK_SECRET,`${parts.t}.${raw}`);if(!constantTimeEqual(expected,parts.v1))return json({error:"Invalid signature"},400);
  const event=JSON.parse(raw) as {id:string;type:string;data:{object:any}};const prior=await env.DB.prepare("SELECT event_id FROM stripe_events WHERE event_id=?").bind(event.id).first();if(prior)return json({received:true,duplicate:true});
  if(event.type==='checkout.session.completed'){
    const s=event.data.object,orderId=s.metadata?.order_id; if(orderId){await env.DB.batch([env.DB.prepare("INSERT INTO stripe_events(event_id,event_type) VALUES(?,?)").bind(event.id,event.type),env.DB.prepare("UPDATE orders SET stripe_payment_intent_id=?,customer_name=?,email=?,phone=?,shipping_address_json=?,shipping_cents=?,total_cents=?,payment_status='paid',fulfilment_status='paid',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(s.payment_intent||null,s.customer_details?.name||null,s.customer_details?.email||null,s.customer_details?.phone||null,JSON.stringify(s.shipping_details?.address||s.customer_details?.address||{}),s.total_details?.amount_shipping||0,s.amount_total||0,orderId)]);} 
  } else await env.DB.prepare("INSERT INTO stripe_events(event_id,event_type) VALUES(?,?)").bind(event.id,event.type).run(); return json({received:true});
}

async function contact(req:Request,env:Env){const b=await req.json().catch(()=>({})) as Record<string,unknown>;const name=cleanText(b.name,100),email=cleanText(b.email,180),message=cleanText(b.message,3000);if(!name||!email.includes('@')||!message)return json({error:"Please complete the required fields"},400);await env.DB.prepare("INSERT INTO contact_enquiries(id,name,email,phone,subject,order_number,message) VALUES(?,?,?,?,?,?,?)").bind(id(),name,email,cleanText(b.phone,40),cleanText(b.subject,120),cleanText(b.order_number,80),message).run();return json({ok:true});}

async function adminSetup(req:Request,env:Env){if(req.headers.get('X-Setup-Secret')!==env.ADMIN_SETUP_SECRET)return json({error:'Forbidden'},403);const count=await env.DB.prepare("SELECT count(*) total FROM admins").first<{total:number}>();if((count?.total||0)>0)return json({error:'Admin already exists'},409);const b=await req.json() as {email?:string,password?:string};if(!b.email||!b.password||b.password.length<12)return json({error:'Use a valid email and password of at least 12 characters'},400);const iterations=100000;const salt=crypto.getRandomValues(new Uint8Array(16));const hash=await pbkdf2(b.password,salt,iterations);await env.DB.prepare("INSERT INTO admins(id,email,password_hash,password_salt,iterations) VALUES(?,?,?,?,?)").bind(id(),b.email.toLowerCase(),hash,b64(salt),iterations).run();return json({ok:true});}
async function adminLogin(req:Request,env:Env){const b=await req.json().catch(()=>({})) as {email?:string,password?:string,turnstileToken?:string};const ip=await sha256(req.headers.get('CF-Connecting-IP')||'local');const attempts=await env.DB.prepare("SELECT count(*) total FROM login_attempts WHERE ip_hash=? AND success=0 AND attempted_at>datetime('now','-15 minutes')").bind(ip).first<{total:number}>();if((attempts?.total||0)>=8)return json({error:'Too many attempts. Try again later.'},429);if(!await verifyTurnstile(req,env,b.turnstileToken||''))return json({error:'Verification failed'},400);const admin=await env.DB.prepare("SELECT id,password_hash,password_salt,iterations FROM admins WHERE email=? AND active=1").bind((b.email||'').toLowerCase()).first<{id:string,password_hash:string,password_salt:string,iterations:number}>();const candidate=admin?await pbkdf2(b.password||'',fromB64(admin.password_salt),admin.iterations):'';const ok=!!admin&&constantTimeEqual(candidate,admin.password_hash);await env.DB.prepare("INSERT INTO login_attempts(ip_hash,success) VALUES(?,?)").bind(ip,ok?1:0).run();if(!ok)return json({error:'Invalid email or password'},401);const token=b64(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare("INSERT INTO admin_sessions(id,admin_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+12 hours'))").bind(id(),admin!.id,await sha256(token)).run();return json({ok:true},200,{"Set-Cookie":`vk_admin=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`});}
async function adminLogout(req:Request,env:Env){const raw=req.headers.get('Cookie')?.match(/(?:^|; )vk_admin=([^;]+)/)?.[1];if(raw)await env.DB.prepare("DELETE FROM admin_sessions WHERE token_hash=?").bind(await sha256(raw)).run();return json({ok:true},200,{"Set-Cookie":"vk_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0"});}
async function adminDashboard(env:Env){const [today,week,products,low,recent]=await Promise.all([env.DB.prepare("SELECT count(*) orders,COALESCE(sum(total_cents),0) revenue FROM orders WHERE payment_status='paid' AND date(created_at)=date('now')").first(),env.DB.prepare("SELECT count(*) orders,COALESCE(sum(total_cents),0) revenue FROM orders WHERE payment_status='paid' AND created_at>datetime('now','-7 days')").first(),env.DB.prepare("SELECT count(*) total FROM products WHERE active=1").first(),env.DB.prepare("SELECT count(*) total FROM products WHERE active=1 AND stock<=low_stock_threshold").first(),env.DB.prepare("SELECT order_number,customer_name,total_cents,payment_status,fulfilment_status,created_at FROM orders ORDER BY created_at DESC LIMIT 10").all()]);return json({today,week,products,low_stock:low,recent_orders:recent.results});}
async function adminProducts(req:Request,env:Env){if(req.method==='GET'){const products=await env.DB.prepare("SELECT p.*,COALESCE(c.name,'Uncategorised') category_name FROM products p LEFT JOIN product_categories pc ON pc.product_id=p.id LEFT JOIN categories c ON c.id=pc.category_id ORDER BY p.display_order,p.name").all();return json({products:products.results});}const b=await req.json() as Record<string,unknown>;const productId=cleanText(b.id,80)||id(),name=cleanText(b.name,160),slug=cleanText(b.slug,180),sku=cleanText(b.sku,100);if(!name||!slug||!sku)return json({error:'Name, slug and SKU are required'},400);await env.DB.prepare("INSERT INTO products(id,name,slug,sku,price_cents,sale_price_cents,short_description,stock,featured,best_seller,active,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET name=excluded.name,slug=excluded.slug,sku=excluded.sku,price_cents=excluded.price_cents,sale_price_cents=excluded.sale_price_cents,short_description=excluded.short_description,stock=excluded.stock,featured=excluded.featured,best_seller=excluded.best_seller,active=excluded.active,updated_at=CURRENT_TIMESTAMP").bind(productId,name,slug,sku,Number(b.price_cents)||0,b.sale_price_cents?Number(b.sale_price_cents):null,cleanText(b.short_description,500),Number(b.stock)||0,b.featured?1:0,b.best_seller?1:0,b.active===false?0:1).run();return json({ok:true,id:productId});}
async function uploadMedia(req:Request,env:Env){const form=await req.formData();const file=form.get('file');if(!(file instanceof File))return json({error:'File required'},400);if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))return json({error:'Use JPEG, PNG, WebP or AVIF up to 5MB'},400);const ext=file.name.split('.').pop()?.toLowerCase()||'bin',key=`uploads/${new Date().toISOString().slice(0,10)}/${id()}.${ext}`;await env.MEDIA_BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type},customMetadata:{originalName:file.name}});return json({key,url:`/media/${key}`});}

async function api(req:Request,env:Env){const u=new URL(req.url),path=u.pathname;
  if(path==='/api/catalogue'&&req.method==='GET')return catalogue(env);if(path==='/api/checkout'&&req.method==='POST')return checkout(req,env);if(path==='/api/stripe/webhook'&&req.method==='POST')return webhook(req,env);if(path==='/api/contact'&&req.method==='POST')return contact(req,env);if(path==='/api/admin/setup'&&req.method==='POST')return adminSetup(req,env);if(path==='/api/admin/login'&&req.method==='POST')return adminLogin(req,env);if(path==='/api/admin/logout'&&req.method==='POST')return adminLogout(req,env);
  if(path.startsWith('/api/admin/')){const admin=await requireAdmin(req,env);if(!admin)return json({error:'Unauthorised'},401);if(req.method!=='GET'&&req.headers.get('Origin')&&req.headers.get('Origin')!==new URL(env.APP_URL).origin)return json({error:'Invalid origin'},403);if(path==='/api/admin/me')return json({authenticated:true,admin});if(path==='/api/admin/dashboard')return adminDashboard(env);if(path==='/api/admin/products')return adminProducts(req,env);if(path==='/api/admin/media'&&req.method==='POST')return uploadMedia(req,env);}
  return json({error:'Not found'},404);
}

export default {async fetch(req:Request,env:Env):Promise<Response>{const url=new URL(req.url);let response:Response;if(url.pathname.startsWith('/api/'))response=await api(req,env);else if(url.pathname.startsWith('/media/')){const key=url.pathname.slice(7),obj=await env.MEDIA_BUCKET.get(key);response=obj?new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=31536000, immutable'}}):new Response('Not found',{status:404});}else{response=await env.ASSETS.fetch(req);if(response.status===404)response=await env.ASSETS.fetch(new Request(new URL('/',url),req));}const h=new Headers(response.headers);Object.entries(corsHeaders).forEach(([k,v])=>h.set(k,v));return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h});}};
