import { FormEvent, useEffect, useState } from "react";
import { api } from "./api";

type Row = Record<string, any>;
type Tab = "Dashboard"|"Products"|"Lollies"|"Jar Sizes"|"Orders"|"Website"|"Shipping"|"Settings";
const tabs:Tab[]=["Dashboard","Products","Lollies","Jar Sizes","Orders","Website","Shipping","Settings"];
const money=(c:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format((Number(c)||0)/100);
const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

function Brand(){return <a className="brand" href="/"><span className="brand-mark">VK</span><span><b>VikingKing</b><small>LOLLIE PICK 'N' MIX</small></span></a>}
function Field({label,name,value,type="text",onChange,required=false}:{label:string;name:string;value:any;type?:string;onChange:(name:string,value:any)=>void;required?:boolean}){return <label>{label}<input name={name} type={type} value={value??""} required={required} onChange={e=>onChange(name,type==="number"?Number(e.target.value):e.target.value)}/></label>}
function Toggle({label,name,value,onChange}:{label:string;name:string;value:any;onChange:(name:string,value:any)=>void}){return <label className="admin-toggle"><input type="checkbox" checked={value!==false&&value!==0} onChange={e=>onChange(name,e.target.checked)}/>{label}</label>}

export default function AdminPanel(){
  const [auth,setAuth]=useState<boolean|null>(null),[tab,setTab]=useState<Tab>("Dashboard"),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [dashboard,setDashboard]=useState<Row>({}),[products,setProducts]=useState<Row[]>([]),[categories,setCategories]=useState<Row[]>([]),[lollies,setLollies]=useState<Row[]>([]),[jars,setJars]=useState<Row[]>([]),[orders,setOrders]=useState<Row[]>([]),[settings,setSettings]=useState<Record<string,string>>({}),[shipping,setShipping]=useState<Row[]>([]),[editor,setEditor]=useState<Row|null>(null);
  const refresh=async()=>{const [d,p,l,j,o,s,sh]=await Promise.all([api.adminDashboard(),api.adminProducts(),api.adminLollies(),api.adminJars(),api.adminOrders(),api.adminSiteSettings(),api.adminShipping()]);setDashboard(d);setProducts(p.products);setCategories(p.categories);setLollies(l.lollies);setJars(j.jars);setOrders(o.orders);setSettings(s.settings);setShipping(sh.shipping)};
  useEffect(()=>{api.adminMe().then(()=>{setAuth(true);refresh()}).catch(()=>setAuth(false))},[]);
  const change=(name:string,value:any)=>setEditor(old=>({...old,[name]:value}));
  const flash=(message:string)=>{setNotice(message);setTimeout(()=>setNotice(""),3500)};
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api.adminLogin(String(f.get("email")),String(f.get("password")));setAuth(true);await refresh()}catch(x){setError(x instanceof Error?x.message:"Login failed")}}
  async function upload(file?:File){if(!file)return;try{const result=await api.uploadMedia(file);change("image_url",result.url);flash("Image uploaded") }catch(x){setError(x instanceof Error?x.message:"Upload failed")}}
  async function saveProduct(e:FormEvent){e.preventDefault();if(!editor)return;await api.saveProduct({...editor,slug:editor.slug||slugify(editor.name||""),price_cents:Number(editor.price_cents)||0,stock:Number(editor.stock)||0});setEditor(null);await refresh();flash("Product saved")}
  async function deleteProduct(){if(!editor?.id||!confirm(`Delete ${editor.name}? This cannot be undone.`))return;try{await api.deleteProduct(editor.id);setEditor(null);await refresh();flash("Product deleted")}catch(x){setError(x instanceof Error?x.message:"Unable to delete product")}}
  async function saveLolly(e:FormEvent){e.preventDefault();if(!editor)return;await api.saveLolly({...editor,slug:editor.slug||slugify(editor.name||""),stock:Number(editor.stock)||0});setEditor(null);await refresh();flash("Lolly saved")}
  async function saveJar(e:FormEvent){e.preventDefault();if(!editor)return;await api.saveJar({...editor,price_cents:Number(editor.price_cents)||0,max_selections:Number(editor.max_selections)||1});setEditor(null);await refresh();flash("Jar size saved")}
  async function saveOrder(order:Row){await api.saveOrder(order);await refresh();flash("Order updated")}
  async function saveWebsite(e:FormEvent){e.preventDefault();await api.saveSiteSettings(settings);flash("Website settings saved")}
  async function saveShipping(row:Row){await api.saveShipping(row);await refresh();flash("Shipping method saved")}
  async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const current=String(f.get("current_password")||""),next=String(f.get("new_password")||""),confirm=String(f.get("confirm_password")||"");if(next!==confirm){setError("New passwords do not match");return}try{await api.changePassword(current,next);flash("Password changed. Please sign in again.");setTimeout(()=>location.reload(),1200)}catch(x){setError(x instanceof Error?x.message:"Unable to change password")}}
  if(auth===null)return <div className="admin-loading">Loading secure admin…</div>;
  if(!auth)return <div className="admin-login"><Brand/><form onSubmit={login}><span className="eyebrow">SECURE STORE ADMIN</span><h1>Welcome back</h1><label>Username<input name="email" type="text" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="button primary">SIGN IN</button>{error&&<small className="admin-error">{error}</small>}</form><a href="/">← Return to store</a></div>;
  return <div className="admin-shell"><aside><Brand/><nav>{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>{setTab(x);setEditor(null);setError("")}}>{x}</button>)}</nav><button onClick={()=>api.adminLogout().then(()=>location.reload())}>Sign out</button></aside><main>{notice&&<div className="admin-notice">{notice}</div>}{error&&<div className="admin-error-banner">{error}<button onClick={()=>setError("")}>×</button></div>}<div className="admin-title"><div><span className="eyebrow">STORE ADMINISTRATION</span><h1>{tab}</h1></div><a className="button outline" href="/">View store</a></div>
    {tab==="Dashboard"&&<><div className="stats"><article><small>Today's orders</small><b>{dashboard?.today?.orders||0}</b></article><article><small>Revenue today</small><b>{money(dashboard?.today?.revenue||0)}</b></article><article><small>Active products</small><b>{dashboard?.products?.total||0}</b></article><article><small>Low stock</small><b>{dashboard?.low_stock?.total||0}</b></article></div><section className="admin-card"><h2>Store overview</h2><p>Use the menu to manage products, mix choices, orders, website content and shipping.</p></section></>}
    {tab==="Products"&&<section className="admin-card"><div className="admin-card-head"><h2>Products and offers</h2><button className="button primary" onClick={()=>setEditor({kind:"product",active:true,stock:100,price_cents:0,image_url:"/hero-jar.webp"})}>+ ADD PRODUCT</button></div><div className="admin-table"><div className="table-head"><span>Product</span><span>SKU</span><span>Price</span><span>Stock</span><span>Status</span><span/></div>{products.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.category_name}</small></span><span>{p.sku}</span><span>{money(p.sale_price_cents??p.price_cents)}</span><span>{p.stock}</span><span className={p.active?"status live":"status"}>{p.active?"Active":"Hidden"}</span><button onClick={()=>setEditor({...p,kind:"product",active:!!p.active})}>Edit</button></div>)}</div></section>}
    {tab==="Lollies"&&<section className="admin-card"><div className="admin-card-head"><h2>Lolly flavours</h2><button className="button primary" onClick={()=>setEditor({kind:"lolly",available:true,stock:100})}>+ ADD LOLLY</button></div><div className="admin-table compact"><div className="table-head"><span>Name</span><span>Category</span><span>Stock</span><span>Status</span><span/></div>{lollies.map(l=><div key={l.id}><span><b>{l.name}</b></span><span>{l.category}</span><span>{l.stock}</span><span className={l.available?"status live":"status"}>{l.available?"Available":"Hidden"}</span><button onClick={()=>setEditor({...l,kind:"lolly",available:!!l.available})}>Edit</button></div>)}</div></section>}
    {tab==="Jar Sizes"&&<section className="admin-card"><div className="admin-card-head"><h2>Jar builder sizes</h2><button className="button primary" onClick={()=>setEditor({kind:"jar",available:true,price_cents:0,max_selections:6,image_url:"/hero-jar.webp"})}>+ ADD JAR SIZE</button></div><div className="admin-table compact"><div className="table-head"><span>Name</span><span>Volume</span><span>Price</span><span>Flavours</span><span/></div>{jars.map(j=><div key={j.id}><span><b>{j.name}</b></span><span>{j.volume}</span><span>{money(j.price_cents)}</span><span>{j.max_selections}</span><button onClick={()=>setEditor({...j,kind:"jar",available:!!j.available})}>Edit</button></div>)}</div></section>}
    {tab==="Orders"&&<section className="admin-card"><h2>Orders</h2>{orders.length===0?<p>No orders yet. Orders will appear here after checkout is enabled.</p>:<div className="order-list">{orders.map((o,index)=><article key={o.id}><div><b>{o.order_number}</b><small>{o.created_at}</small></div><div><span>{o.customer_name||"Customer pending"}</span><small>{o.email}</small></div><b>{money(o.total_cents)}</b><select value={o.fulfilment_status} onChange={e=>setOrders(old=>old.map((x,i)=>i===index?{...x,fulfilment_status:e.target.value}:x))}><option>new</option><option>paid</option><option>packing</option><option>shipped</option><option>completed</option><option>cancelled</option></select><input placeholder="Tracking number" value={o.tracking_number||""} onChange={e=>setOrders(old=>old.map((x,i)=>i===index?{...x,tracking_number:e.target.value}:x))}/><button onClick={()=>saveOrder(orders[index])}>Save</button></article>)}</div>}</section>}
    {tab==="Website"&&<section className="admin-card narrow"><h2>Website content</h2><form className="admin-form" onSubmit={saveWebsite}><Field label="Announcement bar" name="announcement" value={settings.announcement} onChange={(n,v)=>setSettings(x=>({...x,[n]:v}))}/><Field label="Hero heading" name="hero_title" value={settings.hero_title} onChange={(n,v)=>setSettings(x=>({...x,[n]:v}))}/><label>Hero description<textarea value={settings.hero_subtitle||""} onChange={e=>setSettings(x=>({...x,hero_subtitle:e.target.value}))}/></label><Field label="Facebook URL" name="facebook_url" value={settings.facebook_url} onChange={(n,v)=>setSettings(x=>({...x,[n]:v}))}/><Field label="Contact email" name="contact_email" type="email" value={settings.contact_email} onChange={(n,v)=>setSettings(x=>({...x,[n]:v}))}/><label>Shipping note<textarea value={settings.shipping_note||""} onChange={e=>setSettings(x=>({...x,shipping_note:e.target.value}))}/></label><button className="button primary">SAVE WEBSITE</button></form></section>}
    {tab==="Shipping"&&<section className="admin-card"><h2>Shipping methods</h2><div className="shipping-grid">{shipping.map((s,index)=><article key={s.id}><Field label="Label" name="label" value={s.label} onChange={(n,v)=>setShipping(old=>old.map((x,i)=>i===index?{...x,[n]:v}:x))}/><Field label="Rate in cents" name="rate_cents" type="number" value={s.rate_cents} onChange={(n,v)=>setShipping(old=>old.map((x,i)=>i===index?{...x,[n]:v}:x))}/><Toggle label="Enabled" name="enabled" value={s.enabled} onChange={(n,v)=>setShipping(old=>old.map((x,i)=>i===index?{...x,[n]:v}:x))}/><button className="button primary" onClick={()=>saveShipping(shipping[index])}>SAVE</button></article>)}</div><p><small>Special product-specific rates from the supplied client pricing are applied automatically at checkout.</small></p></section>}
    {tab==="Settings"&&<section className="admin-card narrow"><h2>Security settings</h2><form className="admin-form" onSubmit={password}><label>Current password<input name="current_password" type="password" required/></label><label>New password<input name="new_password" type="password" minLength={12} required/></label><label>Confirm new password<input name="confirm_password" type="password" minLength={12} required/></label><button className="button primary">CHANGE PASSWORD</button></form></section>}
    {editor?.kind==="product"&&<div className="admin-modal"><form className="admin-editor" onSubmit={saveProduct}><div className="admin-card-head"><h2>{editor.id?"Edit":"Add"} product</h2><button type="button" onClick={()=>setEditor(null)}>×</button></div><Field label="Name" name="name" value={editor.name} onChange={change} required/><Field label="Slug" name="slug" value={editor.slug} onChange={change}/><Field label="SKU" name="sku" value={editor.sku} onChange={change} required/><Field label="Price in cents" name="price_cents" type="number" value={editor.price_cents} onChange={change} required/><Field label="Standard postage in cents" name="standard_postage_cents" type="number" value={editor.standard_postage_cents} onChange={change}/><Field label="Express postage in cents" name="express_postage_cents" type="number" value={editor.express_postage_cents} onChange={change}/><Field label="Stock" name="stock" type="number" value={editor.stock} onChange={change}/><label>Category<select value={editor.category_id||""} onChange={e=>change("category_id",e.target.value)}><option value="">Uncategorised</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Short description<textarea value={editor.short_description||""} onChange={e=>change("short_description",e.target.value)}/></label><Field label="Image URL" name="image_url" value={editor.image_url} onChange={change}/><label>Upload image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>upload(e.target.files?.[0])}/></label><Toggle label="Active" name="active" value={editor.active} onChange={change}/><Toggle label="Featured" name="featured" value={editor.featured} onChange={change}/><Toggle label="Best seller" name="best_seller" value={editor.best_seller} onChange={change}/><div className="admin-editor-actions">{editor.id&&<button type="button" className="button danger" onClick={deleteProduct}>DELETE PRODUCT</button>}<button className="button primary">SAVE PRODUCT</button></div></form></div>}
    {editor?.kind==="lolly"&&<div className="admin-modal"><form className="admin-editor" onSubmit={saveLolly}><div className="admin-card-head"><h2>{editor.id?"Edit":"Add"} lolly</h2><button type="button" onClick={()=>setEditor(null)}>×</button></div><Field label="Name" name="name" value={editor.name} onChange={change} required/><Field label="Slug" name="slug" value={editor.slug} onChange={change}/><Field label="Category" name="category" value={editor.category} onChange={change}/><Field label="Stock" name="stock" type="number" value={editor.stock} onChange={change}/><label>Description<textarea value={editor.description||""} onChange={e=>change("description",e.target.value)}/></label><Field label="Dietary information" name="dietary_info" value={editor.dietary_info} onChange={change}/><Field label="Allergen information" name="allergen_info" value={editor.allergen_info} onChange={change}/><Field label="Image URL" name="image_url" value={editor.image_url} onChange={change}/><label>Upload image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>upload(e.target.files?.[0])}/></label><Toggle label="Available" name="available" value={editor.available} onChange={change}/><button className="button primary">SAVE LOLLY</button></form></div>}
    {editor?.kind==="jar"&&<div className="admin-modal"><form className="admin-editor" onSubmit={saveJar}><div className="admin-card-head"><h2>{editor.id?"Edit":"Add"} jar size</h2><button type="button" onClick={()=>setEditor(null)}>×</button></div><Field label="Name" name="name" value={editor.name} onChange={change} required/><Field label="Volume" name="volume" value={editor.volume} onChange={change} required/><Field label="Price in cents" name="price_cents" type="number" value={editor.price_cents} onChange={change}/><Field label="Maximum flavour choices" name="max_selections" type="number" value={editor.max_selections} onChange={change}/><label>Description<textarea value={editor.description||""} onChange={e=>change("description",e.target.value)}/></label><Field label="Image URL" name="image_url" value={editor.image_url} onChange={change}/><label>Upload image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>upload(e.target.files?.[0])}/></label><Toggle label="Available" name="available" value={editor.available} onChange={change}/><button className="button primary">SAVE JAR SIZE</button></form></div>}
  </main></div>
}
