import { FormEvent, useEffect, useMemo, useState } from "react";
import { api } from "./api";
import type { CartItem, JarSize, Lolly, Product } from "./types";

const fallbackProducts: Product[] = [
  {id:"prod-550",name:"550ml Pick n Mix Jar",slug:"550ml-pick-n-mix",sku:"VK-550",price_cents:1495,sale_price_cents:null,short_description:"Choose up to six flavours.",category_name:"Pick n Mix",image_url:null,stock:100,featured:1,best_seller:1},
  {id:"prod-1l",name:"1L Pick n Mix Jar",slug:"1l-pick-n-mix",sku:"VK-1L",price_cents:2495,sale_price_cents:null,short_description:"Choose up to eight flavours.",category_name:"Lolly Jars",image_url:null,stock:100,featured:1,best_seller:1},
  {id:"prod-sour",name:"Sour Power Mix",slug:"sour-mix",sku:"VK-SOUR",price_cents:1695,sale_price_cents:null,short_description:"A colourful sour selection.",category_name:"Sour Lollies",image_url:null,stock:50,featured:1,best_seller:0},
  {id:"prod-gummy",name:"Gummy Goodness Mix",slug:"gummy-mix",sku:"VK-GUMMY",price_cents:1695,sale_price_cents:null,short_description:"A fun gummy selection.",category_name:"Gummies",image_url:null,stock:50,featured:1,best_seller:0},
  {id:"prod-sweet",name:"Sweet Classics Mix",slug:"sweet-mix",sku:"VK-SWEET",price_cents:1595,sale_price_cents:null,short_description:"Something sweet for everyone.",category_name:"Retro Lollies",image_url:null,stock:50,featured:0,best_seller:0},
  {id:"prod-party",name:"Party Hero Pack",slug:"party-mix",sku:"VK-PARTY",price_cents:3995,sale_price_cents:null,short_description:"Party-ready sweet selection.",category_name:"Party Packs",image_url:null,stock:30,featured:0,best_seller:0}
];
const fallbackJars: JarSize[]=[{id:"jar-550",name:"550ml Jar",volume:"550ml",description:"Choose up to six flavours.",price_cents:1495,max_selections:6,image_url:null,available:1},{id:"jar-1l",name:"1 Litre Jar",volume:"1 Litre",description:"Choose up to eight flavours.",price_cents:2495,max_selections:8,image_url:null,available:1}];
const lollyNames=["Gummy Bears","Cola Bottles","Sour Worms","Peach Rings","Snakes","Milk Bottles","Jelly Beans","Strawberries and Cream"];
const fallbackLollies: Lolly[]=lollyNames.map((name,i)=>({id:`lol-${i}`,name,description:"A colourful favourite.",category:i===2?"Sour":"Gummies",dietary_info:"Owner to confirm",allergen_info:"Owner to confirm",image_url:null,available:1}));
const emojis=["🍬","🍭","🍋","🐻","🍓","🎉","🍫","🌈"];
const money=(c:number)=>new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(c/100);

function Brand(){return <a className="brand" href="#home"><span className="brand-mark">VK</span><span><b>VikingKing</b><small>LOLLIE PICK 'N' MIX</small></span></a>}

function Store(){
  const [products,setProducts]=useState(fallbackProducts),[jars,setJars]=useState(fallbackJars),[lollies,setLollies]=useState(fallbackLollies),[settings,setSettings]=useState<Record<string,string>>({});
  const [cart,setCart]=useState<CartItem[]>(()=>JSON.parse(localStorage.getItem("vk-cart")||"[]")),[cartOpen,setCartOpen]=useState(false),[menu,setMenu]=useState(false),[filter,setFilter]=useState("All"),[search,setSearch]=useState("");
  const [step,setStep]=useState(1),[jar,setJar]=useState<JarSize|null>(null),[selected,setSelected]=useState<Lolly[]>([]),[notice,setNotice]=useState("");
  useEffect(()=>{api.catalogue().then(d=>{setProducts(d.products);setJars(d.jars);setLollies(d.lollies);setSettings(d.settings)}).catch(()=>{})},[]);
  useEffect(()=>localStorage.setItem("vk-cart",JSON.stringify(cart)),[cart]);
  useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get('checkout')==='success'){setNotice('Payment received - thank you for your order!');setCart([])}else if(p.get('checkout')==='cancelled')setNotice('Checkout was cancelled. Your bag is still saved.')},[]);
  const categories=["All",...new Set(products.map(p=>p.category_name))];
  const shown=useMemo(()=>products.filter(p=>(filter==="All"||p.category_name===filter)&&(p.name+p.category_name).toLowerCase().includes(search.toLowerCase())),[products,filter,search]);
  const add=(p:Product)=>{setCart(old=>{const found=old.find(x=>x.key===p.id);return found?old.map(x=>x.key===p.id?{...x,quantity:x.quantity+1}:x):[...old,{key:p.id,product_id:p.id,name:p.name,unit_price_cents:p.sale_price_cents??p.price_cents,quantity:1,image_url:p.image_url}]});setCartOpen(true)};
  const addMix=()=>{if(!jar||!selected.length)return;setCart(old=>[...old,{key:crypto.randomUUID(),jar_size_id:jar.id,name:`Custom ${jar.volume} Pick n Mix`,unit_price_cents:jar.price_cents,quantity:1,lolly_ids:selected.map(x=>x.id),lolly_names:selected.map(x=>x.name)}]);setStep(1);setJar(null);setSelected([]);setCartOpen(true)};
  const change=(key:string,n:number)=>setCart(old=>old.map(x=>x.key===key?{...x,quantity:x.quantity+n}:x).filter(x=>x.quantity>0));
  const checkout=async()=>{try{const {url}=await api.checkout(cart.map(x=>({product_id:x.product_id,jar_size_id:x.jar_size_id,quantity:x.quantity,lolly_ids:x.lolly_ids})));location.href=url}catch(e){setNotice(e instanceof Error?e.message:"Checkout failed")}};
  const total=cart.reduce((s,x)=>s+x.unit_price_cents*x.quantity,0);
  return <>
    <div className="announcement">🍭 {settings.announcement||"Fresh Pick n Mix Lollies Delivered Australia Wide"}</div>
    <header><Brand/><nav className={menu?"open":""}><a href="#home">Home</a><a href="#shop">Shop</a><a className="pink" href="#mix">Build Your Mix</a><a href="#about">About Us</a><a href="#faq">FAQ</a><a href="#contact">Contact</a></nav><div className="header-buttons"><button className="bag" onClick={()=>setCartOpen(true)}>Bag <b>{cart.reduce((s,x)=>s+x.quantity,0)}</b></button><button className="hamburger" onClick={()=>setMenu(!menu)}>☰</button></div></header>
    {notice&&<div className="notice" onClick={()=>setNotice("")}>{notice} <b>×</b></div>}
    <main>
      <section className="hero" id="home"><div><span className="eyebrow">MIXED WITH JOY • DELIVERED AUSTRALIA WIDE</span><h1>PICK.<br/><em>MIX.</em> ENJOY.</h1><p>{settings.hero_subtitle||"Build your perfect lolly mix and get it delivered straight to your door. Your jar, your favourites, your way."}</p><div className="actions"><a className="button primary" href="#mix">BUILD YOUR MIX →</a><a className="button outline" href="#shop">SHOP LOLLY JARS</a></div><div className="trust"><span>✓ Packed fresh</span><span>✓ Secure Stripe checkout</span><span>✓ Australian business</span></div></div><div className="hero-image"><img src="/hero-jar.png" alt="VikingKing jar filled with colourful pick and mix lollies"/><span>100%<small>YOUR MIX</small></span></div></section>
      <section className="section" id="shop"><div className="section-title"><div><span className="eyebrow">CROWD PLEASERS</span><h2>Sweet favourites</h2></div><input className="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search sweets..."/></div><div className="chips">{categories.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="product-grid">{shown.map((p,i)=><article className="product-card" key={p.id}><div className="product-photo">{p.image_url?<img src={p.image_url} alt={p.name}/>:<span>{emojis[i%emojis.length]}</span>} {p.best_seller?<b>BEST SELLER</b>:null}</div><h3>{p.name}</h3><small>{p.short_description}</small><div><strong>{money(p.sale_price_cents??p.price_cents)}</strong><button onClick={()=>add(p)}>+</button></div></article>)}</div></section>
      <section className="builder-section" id="mix"><div className="builder-copy"><span className="eyebrow yellow">MADE BY YOU</span><h2>Build your dream jar.</h2><p>Choose your jar, fill it with favourites and we'll mix it fresh just for you.</p></div><div className="builder"><div className="progress"><span className={step>=1?"on":""}>1 Jar</span><i/><span className={step>=2?"on":""}>2 Lollies</span><i/><span className={step>=3?"on":""}>3 Review</span></div>{step===1&&<div><span className="eyebrow">STEP ONE</span><h3>Choose your jar</h3><div className="jar-grid">{jars.map(j=><button className={jar?.id===j.id?"selected":""} onClick={()=>setJar(j)} key={j.id}><span>🍭</span><b>{j.name}</b><small>{j.description}</small><strong>{money(j.price_cents)}</strong></button>)}</div><div className="builder-nav"><span/><button disabled={!jar} onClick={()=>setStep(2)} className="button primary">CHOOSE LOLLIES →</button></div></div>}{step===2&&jar&&<div><span className="eyebrow">STEP TWO</span><h3>Pick your favourites</h3><p><b>{selected.length} of {jar.max_selections}</b> flavours selected</p><div className="meter"><i style={{width:`${selected.length/jar.max_selections*100}%`}}/></div><div className="lolly-grid">{lollies.map((l,i)=>{const on=selected.some(x=>x.id===l.id);return <button className={on?"selected":""} onClick={()=>setSelected(s=>on?s.filter(x=>x.id!==l.id):s.length<jar.max_selections?[...s,l]:s)} key={l.id}><span>{emojis[i%emojis.length]}</span><b>{l.name}</b></button>})}</div><div className="builder-nav"><button className="button outline" onClick={()=>setStep(1)}>← BACK</button><button disabled={!selected.length} className="button primary" onClick={()=>setStep(3)}>REVIEW MIX →</button></div></div>}{step===3&&jar&&<div><span className="eyebrow">FINAL STEP</span><h3>Your mix looks delicious!</h3><div className="review"><p><span>Jar</span><b>{jar.name}</b></p><p><span>Flavours</span><b>{selected.length}</b></p><div>{selected.map(x=><small key={x.id}>{x.name}</small>)}</div><p><span>Total</span><b>{money(jar.price_cents)}</b></p></div><div className="builder-nav"><button className="button outline" onClick={()=>setStep(2)}>← EDIT</button><button className="button primary" onClick={addMix}>ADD MY MIX →</button></div></div>}</div></section>
      <section className="story" id="about"><div className="story-photo"><img src="/hero-jar.png" alt="Colourful VikingKing lolly jar"/></div><div><span className="eyebrow">OUR STORY</span><h2>A jar full of joy.</h2><p>VikingKing Lollie Pick n Mix makes it easy to build a lolly jar filled with the treats you actually love.</p><p>Whether you're treating yourself, surprising someone special or planning a party, every mix is packed to bring more colour and joy to the moment.</p><a href={settings.facebook_url||"https://www.facebook.com/vikingkinglolliepicknmix"} target="_blank">Follow VikingKing on Facebook →</a></div></section>
      <section className="section faq" id="faq"><div><span className="eyebrow">NEED TO KNOW</span><h2>Frequently asked questions</h2></div><div>{["How does Pick n Mix work?","How many lollies can I choose?","Do you deliver Australia wide?","What allergens are present?"].map((q,i)=><details key={q}><summary>{q}</summary><p>{["Choose your jar, select your favourites, review the mix and add it to your bag.","Your limit is shown after choosing a jar size.","Delivery details and rates will be confirmed by the store owner.","Ingredients vary. Please check the confirmed product information before ordering."][i]}</p></details>)}</div></section>
      <Contact/>
    </main>
    <footer><div><Brand/><p>Pick your favourites. Mix them your way. Enjoy every bite.</p></div><div><b>SHOP</b><a href="#shop">All products</a><a href="#mix">Build Your Mix</a></div><div><b>HELP</b><a href="#faq">FAQs</a><a href="#contact">Contact</a></div><div><b>FOLLOW</b><a target="_blank" href={settings.facebook_url||"https://www.facebook.com/vikingkinglolliepicknmix"}>Facebook ↗</a><a href="/admin">Store admin</a></div></footer>
    <div className={cartOpen?"overlay show":"overlay"} onClick={()=>setCartOpen(false)}/><aside className={cartOpen?"cart open":"cart"}><div className="cart-head"><div><span className="eyebrow">YOUR SWEET STASH</span><h2>Your bag</h2></div><button onClick={()=>setCartOpen(false)}>×</button></div><div className="cart-list">{cart.length===0?<div className="empty">🍭<h3>Your bag is feeling light</h3></div>:cart.map(x=><article key={x.key}><span>🍬</span><div><b>{x.name}</b>{x.lolly_names&&<small>{x.lolly_names.join(", ")}</small>}<div className="quantity"><button onClick={()=>change(x.key,-1)}>−</button>{x.quantity}<button onClick={()=>change(x.key,1)}>+</button></div></div><strong>{money(x.unit_price_cents*x.quantity)}</strong></article>)}</div>{cart.length>0&&<div className="cart-total"><p><b>Subtotal</b><b>{money(total)}</b></p><small>Shipping is calculated securely at checkout.</small><button onClick={checkout} className="button primary">SECURE CHECKOUT →</button></div>}</aside>
  </>
}

function Contact(){const [status,setStatus]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api.contact(Object.fromEntries(f.entries()));setStatus("Thanks! Your message has been received.");e.currentTarget.reset()}catch(e){setStatus(e instanceof Error?e.message:"Unable to send")}}return <section className="contact" id="contact"><div><span className="eyebrow">SAY HELLO</span><h2>Got a sweet question?</h2><p>Ask about an order, party packs, gifts or anything else.</p></div><form onSubmit={submit}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Subject<select name="subject"><option>General enquiry</option><option>Order question</option><option>Party or event</option></select></label><label>Message<textarea name="message" rows={4} required/></label><button className="button primary">SEND MESSAGE →</button><small>{status}</small></form></section>}

function Admin(){const [auth,setAuth]=useState<boolean|null>(null),[data,setData]=useState<any>(null),[products,setProducts]=useState<Product[]>([]),[error,setError]=useState("");const load=()=>Promise.all([api.adminDashboard(),api.adminProducts()]).then(([d,p])=>{setData(d);setProducts(p.products)});useEffect(()=>{api.adminMe().then(()=>{setAuth(true);load()}).catch(()=>setAuth(false))},[]);async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api.adminLogin(String(f.get('email')),String(f.get('password')));setAuth(true);load()}catch(e){setError(e instanceof Error?e.message:"Login failed")}}if(auth===null)return <div className="admin-loading">Loading...</div>;if(!auth)return <div className="admin-login"><Brand/><form onSubmit={login}><span className="eyebrow">SECURE STORE ADMIN</span><h1>Welcome back</h1><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label><button className="button primary">SIGN IN</button><small>{error}</small></form><a href="/">← Return to store</a></div>;return <div className="admin-shell"><aside><Brand/><nav><b>Dashboard</b><span>Products</span><span>Lollies</span><span>Jar Sizes</span><span>Orders</span><span>Website</span><span>Shipping</span><span>Settings</span></nav><button onClick={()=>api.adminLogout().then(()=>location.reload())}>Sign out</button></aside><main><div className="admin-title"><div><span className="eyebrow">STORE ADMINISTRATION</span><h1>Dashboard</h1></div><a className="button outline" href="/">View store</a></div><div className="stats"><article><small>Today's orders</small><b>{data?.today?.orders||0}</b></article><article><small>Revenue today</small><b>{money(data?.today?.revenue||0)}</b></article><article><small>Products</small><b>{data?.products?.total||0}</b></article><article><small>Low stock</small><b>{data?.low_stock?.total||0}</b></article></div><section className="admin-card"><div className="admin-title"><h2>Products</h2><button className="button primary">+ ADD PRODUCT</button></div><div className="product-table"><div className="table-head"><span>Product</span><span>SKU</span><span>Price</span><span>Stock</span><span>Status</span></div>{products.map(p=><div key={p.id}><span><b>{p.name}</b><small>{p.category_name}</small></span><span>{p.sku}</span><span>{money(p.sale_price_cents??p.price_cents)}</span><span>{p.stock}</span><span className={p.stock>0?"status live":"status"}>{p.stock>0?"Active":"Out of stock"}</span></div>)}</div></section></main></div>}

export default function App(){return location.pathname.startsWith('/admin')?<Admin/>:<Store/>}
